### ISSUE TITLE
LaTeX does not render properly

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/frc-docs-translations#11]
Take a look at these images. Does anyone have any ideas why this is happening?

![image](https://user-images.githubusercontent.com/3799260/87466044-7417bd80-c5ca-11ea-9822-81805035f150.png)
![image](https://user-images.githubusercontent.com/3799260/87466045-767a1780-c5ca-11ea-93a4-c37a9f215150.png)

**Comment by calcmogul** [comment]
Looks like it didn't properly escape the backslashes for the pmatrix environment. I can't find that page in English though.

**Comment by Daltz333** [comment]
The issue also only occurs on that page. Other pages are fine. I suspect it's an issue when latex is broken up on multiple newlines

**Comment by AustinShalit** [comment]
Closed by https://github.com/wpilibsuite/frc-docs/pull/885
