### ISSUE TITLE
Deprecation of Transifex API v2 and sunset of Transifex Client

### ISSUE THREAD

**Issue by rffontenelle** [wpilibsuite/frc-docs-translations#30]
The transifex-client as well is going away in November 30, 2022. The new [transifex/cli](https://github.com/transifex/cli) is going to be the new thing. Since the new client is written in Go lang, it won't be installable via Python's requirements.txt,

For more info: https://community.transifex.com/t/postponing-api-2-0-2-5-and-transifex-client-sunset-date/2759

**Comment by Daltz333** [comment]
Blocked by https://github.com/sphinx-doc/sphinx-intl/issues/60
